### ISSUE TITLE
HandWaving icon does not handle `weight="fill"` properly

### ISSUE THREAD

**Issue by pthieu** [phosphor-icons/react#28]
My code:
```
<HandWavingIcon size={32} color="#EDC281" weight="fill" />
```
Results:
![image](https://user-images.githubusercontent.com/2908721/172259157-d22ba875-cda1-4917-b738-1cd96f8e6e1b.png)

By comparison I changed the import to a star and used the same alias (so that we keep the above HTML exactly the same) like so:
```
import {
  Star as HandWavingIcon,
} from 'phosphor-react';
```
results:
![image](https://user-images.githubusercontent.com/2908721/172259135-de120b7c-4cb1-412f-9ba7-393c114015a8.png)

**Comment by rektdeckard** [comment]
In the next release, we'll be improving coverage for `fill` weight across many icons.
