### ISSUE TITLE
Add support for server components

### ISSUE THREAD

**Issue by melkstam** [phosphor-icons/react#32]
With the release of React 18 (and NextJS 13), server components are supported and will most certainly get utilized more going forward. It would be nice of phosphor-react to support this. It does currently seem to be limited by the usage of `React.Context`.

Possible solutions would be to use the `"use client"` directive (https://github.com/reactjs/rfcs/pull/227) or in some way make the context optional.

**Comment by ozgur-dogan** [comment]
+1

**Comment by L-Marcel** [comment]
+1

**Comment by sungvzer** [comment]
+1
One of the best features of Next.js is server components and because Phosphor Icons uses React contexts it cannot be used in a Next 13 project unless a client component is used, which kinda defeats the purpose of server components.

**Comment by rektdeckard** [comment]
Hey all. Looking into this for upcoming 2.0 release 👍

**Comment by its-monotype** [comment]
My favorite icons, I like them so much. I am incredibly grateful to the creators 😍

**Comment by rektdeckard** [comment]
Wondering what people feel would be good default styling in lieu of context server-side -- black, regular weight, 1em size?

**Comment by eIiot** [comment]
+1

**Comment by melkstam** [comment]
> Wondering what people feel would be good default styling in lieu of context server-side -- black, regular weight, 1em size?

I feel like that these are pretty good default values and is what I would expect.

**Comment by rektdeckard** [comment]
Having read and partially 😂  understood the RFC, it seems that a `"use client";` directive essentially "poisons" everything in the subtree, yes? That understood, `IconBase.tsx`, which is the only component referencing `useContext` and called by every icon, just needs a "use client"; at the top, and we force this code into the client bundle. Correct me if I'm wrong about that.

It would be really nice, although maybe quite complex, if we had some sort of conditional directive to allow different behaviors on server- and client-side, a la:
```ts
let defaultValues = { size, weight, color, mirrored };
"if client";
defaultValues = useContext(IconContext);
"endif";
```

**Comment by MatheusPires99** [comment]
Any updates on this topic?

**Comment by rektdeckard** [comment]
Prelim support added in `v2.0.0`, under new package name `@phosphor-icons/react`. Looking at ways in future of not needing to force `IconBase` onto the client, because rendering the entire icon on the server would be sweet but I don't want to break the context use case.

**Comment by thewinger** [comment]
Is there an update?
I see a PR, tried to installed it with Yarn to try it but couldn't, don't know why.

**Comment by dgknca** [comment]
still waiting
