### ISSUE TITLE
"@phosphor-icons/react" was not found in your node_modules. Did you forget to install it?

### ISSUE THREAD

**Issue by hta218** [phosphor-icons/react#44]
Could this be the same issue as #41? I would appreciate any guidance on how to resolve this error.

Error message: 
```bash
The path "@phosphor-icons/react" is imported in app/icons/index.ts but "@phosphor-icons/react" was not found in your node_modules. Did you forget to install it?
```

I'm using the package in a [Remix](https://remix.run/) app
Node version: `v18.15.0`
My `package.json`: `"@phosphor-icons/react": "^2.0.6"`

**Comment by rektdeckard** [comment]
Could be. I have no experience with Remix, but it seems to be a known limitation that ESM-only packages are not supported in server files. Have you tried forcing this into client, per this section of their docs? https://remix.run/docs/en/1.14.3/pages/gotchas#md-importing-esm-packages

This is an ESM-only package at the moment, but I will try and push a UMD build at some point that should be compatible with Remix and anything else still stuck in the pre-ESM era. It boggles the mind that we are still dealing with NodeJS hangovers like this in 2023!

**Comment by hta218** [comment]
Yeah, adding `@phosphor-icons/react` to the `serverDependenciesToBundle` array is ... somehow worked. 
It still throws the error above but the server can be started (before, it kept crashing and the app couldn't be started)

Thank you for taking a look 🤝, guess I'll close this now.

**Comment by vdineva** [comment]
@rektdeckard I'm experiencing similar issue in project- everything works well in the browser but our unit tests using Jest can't find the "@phosphor-icons/react" module. Seems like Jest's support for ESM modules is still in experimental phase: https://jestjs.io/docs/ecmascript-modules
When do you expect the UMD build to be available?

**Comment by rektdeckard** [comment]
I will build and publish with the UMD bundle tomorrow

**Comment by rektdeckard** [comment]
v2.0.8 includes a UMD build, and should be compatible with CJS-based build tooling.
