### ISSUE TITLE
npm install phosphor-react@2.0.6 not working

### ISSUE THREAD

**Issue by shreyas-aw** [phosphor-icons/react#48]
Hi Team, 

It seems `npm install phosphor-react@2.0.6` is not working, giving below error. 

<img width="301" alt="image" src="https://user-images.githubusercontent.com/123137600/230065022-a1e4ef68-8aa9-41e0-b612-33fecfb08281.png">

Can anyone help ? 

cc @rektdeckard

**Comment by rektdeckard** [comment]
The package has been moved under our NPM workspace. It is now `@phosphor-icons/react`.
