### ISSUE TITLE
Refactoring and some suggestions for improvements.

### ISSUE THREAD

**Issue by ronaldosc** [phosphor-icons/react#49]
- I'll bring modifications for start a PR refac of the exportations in the `src/index.ts`, because a lot of lines repeat.
- a proposal for new name of "GameController" because it more generic and I encountered "Joystick" to fit well in this case and compatible with the visual icon.
- at the  `core\src\icons.ts` I think it more comprehensible the legacy icons being presented in the list as such as this example:
```ts
 name: "file-dashed",
    pascal_name: "FileDashed",
    legacy: {
      alias_name: "file-dotted",
      pascal_name: "FileDotted",
      changed_in: 2.0,
    },
```
And the prop `changed_in` a propose for register knowing when the legacy started (the future we don't know).

-------
And some cases that the icon is published the first time, it's not necessary to fill prop `updated_in` cause it occurred at the same time this new implementation.

```ts
  { ...........,
    published_in: 1.4,
    updated_in: 1.4,
  },
```

would be only for this case

```ts
  { ..........,
    published_in: 1.4,
  },
```

******
What do you say about that ?  Can assign me for this work ? **I almost finished it**.

**Comment by ronaldosc** [comment]
@rektdeckard , what you think? We can discuss better if needed. Or with another contributors.

**Comment by ronaldosc** [comment]
The `changed_in` is only for icons that was changed when it occcurs. It's for reference and documentation.

**Comment by ronaldosc** [comment]
about the two fields I've explained above:
 `published_in: 1.4,
 updated_in: 1.4,´

**Comment by rektdeckard** [comment]
The source file is transpiled to much smaller code, which is the only code that is consumed when you install the library. The transpiled code is all that matters in terms of bytes, and the syntax we use in the source file does not change what the bundler will emit.

**Comment by ronaldosc** [comment]
For comparison, with refact the index with .d.ts and map is about 43.4 KB, and the actual version emits  214.0 KB,

**Comment by rektdeckard** [comment]
Can you show me what you are proposing, via an actual PR? I can't talk about this in the abstract. `.d.ts` and sourcemap  files should not be of any concern; they exist only on developers machines and aren't bundled in a compiled app. And if you're using a CDN, you won't be fetching this file.

**Comment by rektdeckard** [comment]
My guess is you mean turning exports like:

```ts
import { default as o } from "./icons/AddressBook.es.js";
import { default as t } from "./icons/AirTrafficControl.es.js";
export { 
  o as AddressBook,
  t as AirTrafficControl
};
```

into 

```ts
export { default as AddressBook } from "./icons/AddressBook.es.js";
export { default as AirTrafficControl } from "./icons/AirTrafficControl.es.js";
```

Because I can't see any terser way to export everything as named, while still providing default exports in icon source files themselves. This really doesn't save many bytes at all, maybe 6 bytes per icon, plus another 10 or so bytes total for the single `export` statement.
