### ISSUE TITLE
lib is not exported from package.json

### ISSUE THREAD

**Issue by xcxooxl** [phosphor-icons/react#50]
I had trouble with tree shaking with next.js so I had to use

```
  modularizeImports: {
    '@phosphor-icons/react': {
      transform: '@phosphor-icons/react/dist/icons/{{member}}',
    },
}
```
in my next.config.js to make the tree shaking work, but that broke IconContext because it tried to import it from icons as well.
so I exported it in package.json and now I can import like so:
import { IconContext } from '@phosphor-icons/react/dist/lib/context'

I think the lib  inside dist should be exported like the icons.

**Comment by rektdeckard** [comment]
I can add the export (I assume you mean add the relevant paths to the `exports` field in `package.json`?), but I don't know what they're smoking at Vercel. This library should be trivially tree shakeable by a competent bundler.

**Comment by JipSterk** [comment]
i also experience this issue with the solution you provided [here](https://github.com/phosphor-icons/react/discussions/51#discussion-5122167) @rektdeckard

**Comment by rektdeckard** [comment]
@JipSterk I don't see that as related. You are trying to use the default import of a package that doesn't have one, that's all.
