### ISSUE TITLE
Invariant Violation: View config getter callback for component `path` must be a function (received `undefined`)

### ISSUE THREAD

**Issue by K0R1NGA69** [phosphor-icons/react#57]
i am getting this error when i try to use any icon from this package ("@phosphor-icons/react": "^2.0.10") it works just fine when i use the previous phosphor-react-native": "^1.1.2".

I am getting the following error
Invariant Violation: View config getter callback for component `path` must be a function (received `undefined`). Make sure to start component names with a capital letter. 

This error is located at:
    in path
    in svg (created by IconBase)
    in IconBase (created by Star)
    in Star (created by UserRecords)
    in RCTView (created by View)
    in View
    in Unknown

My Env:

"react-native": "0.71.8",
"expo": "~48.0.18",

**Comment by rektdeckard** [comment]
@K0R1NGA69 this library does not support React Native, and `phosphor-react-native` is a community port we do not maintain.
