### ISSUE TITLE
Error 504 (Gateway Timeout) when using icon component

### ISSUE THREAD

**Issue by jgcampos1** [phosphor-icons/react#61]
I have this error when using the phosphor-icons lib with vitte, I've used it before with a project with webpack and I've never had this error, does anyone know why?

![image](https://github.com/phosphor-icons/react/assets/62268075/1fdf8d6f-beab-4827-aa6b-4a7b6606dee2)

i use component like this, importing from '@phosphor-icons/react'
![image](https://github.com/phosphor-icons/react/assets/62268075/90414c22-2aba-4f72-b327-da8f76d9a804)

I added this configuration in the json package to try to solve it but without success
![image](https://github.com/phosphor-icons/react/assets/62268075/84faf830-d847-4b4a-b4cb-11dbbd3f6e3a)

**Comment by rektdeckard** [comment]
This is a known bug in the Next.js bundler when dealing with large component libs of thousands of files. If you are on next 13.5.x `experimental`, or 14+, you can use the [optimizePackageImports](https://nextjs.org/docs/app/api-reference/next-config-js/optimizePackageImports) drop-in replacement for `modularizeImports`.
