### ISSUE TITLE
TypeError: Cannot create property 'displayName' on number 'Infinity'

### ISSUE THREAD

**Issue by power-f-GOD** [phosphor-icons/react#79]
`Infinity` is a `number` (and/or reserved word) in JavaScript, hence the `Infinity` icon's name conflicts with the same.

<img width="755" alt="Screenshot 2023-11-13 at 9 21 14 PM" src="https://github.com/phosphor-icons/react/assets/28790485/a4f100a4-d670-4eef-a2e5-5f15b403b270">

This makes my NextJS (14) app build break.

<img width="1301" alt="Screenshot 2023-11-13 at 9 12 27 PM" src="https://github.com/phosphor-icons/react/assets/28790485/e8c5a837-467e-49cb-89c5-f8b1f7f47ac0">

**Comment by rektdeckard** [comment]
Just use import aliasing to rename it to whatever you want. We have addressed this one before, and`Infinity` is not the only JS or web platform global that gets reused.

```js
import { Infinity as InfinityIcon } from "@phosphor-icons/react”;
```

**Comment by power-f-GOD** [comment]
The error occurs during compilation (or should I say in the compiled/built code) independent of whether I'm using the icon or not.

Currently, I am not using the icon, I don't have it imported anywhere.

> ...Infinity is not the only JS or web platform global that gets reused.

That's not good practice, IMO. And even if the global must be "reused" (overridden), then they should, at least, have the same base (data) type.

Now, the compiler sees `Infinity` and reckons it is a number, but it is a RFC in this context.💔

**Comment by markmssd** [comment]
We're running into the same issue, @power-f-GOD did you find a workaround? 🙏🏼

**Comment by rektdeckard** [comment]
@power-f-GOD to clarify what I meant, we will be careful not to use global names *internally*, but it should not matter if we provided aliased named exports that occasionally conflict with globals.

**Comment by markmssd** [comment]
Thanks @rektdeckard ! Let's hope it helps 🤞🏼 As @power-f-GOD mentioned, even if the icon is not used, the error occurs during compilation (in our case, during Jest test runs). Let's see! 🥁

**Comment by rektdeckard** [comment]
Try upgrading to`@phosphor-icons/react@2.0.15`, should have fixed the issue
