### ISSUE TITLE
Icon instance className overwrites context className

### ISSUE THREAD

**Issue by killface** [phosphor-icons/react#83]
If I specify a className in my context provider, eg.
```
    <IconContext.Provider
      value={{ className: 'icon' }}
      ...
   />
```

And then specify a className when I use my icon, eg. `<CalendarCheck className="foo" />`,
... then my icon only gets the `foo` className and I can no longer target the element with the `.icon` selector.

I'd propose bringing in a small library like [clsx](https://www.npmjs.com/package/clsx) and updating IconBase to merge the two className values on the `<svg>` element, eg. `className={clsx(contextClassName, className)}`.

I'd be happy to create a PR with the proposed changes, given a bit of guidance on how to contribute to this project (and an okay for adding a third-party dependency).

**Comment by rektdeckard** [comment]
AFAIC this is the expected behavior in React -- passing explicit props always overrides, not adds. The same is true in vanilla JS with object spread operator, etc. I also do not wish to add any external runtime dependencies to this lib, so I suggest just using a context consumer to get your  context `className` and combine it yourself:

```tsx
<IconContext.Provider value={{ className: 'icon' }}>
  <IconContext.Consumer>
    {({ className }) => (<Cube className={clsx(className, "foo")} />)}
  </IconContext.Consumer>
<IconContext.Provider>
```

**Comment by killface** [comment]
Oh, interesting! I'm somewhat new to React and wasn't aware of the context Consumer. I'll look into that route - is there a way to make it generic so ALL Phosphor Icons get the classNames merged/appended, or will I need to use an `<IconContext.Consumer` around each icon instance where I want this functionality?

Thanks for the prompt response, btw!

**Comment by rektdeckard** [comment]
Sure thing! It isn't possible to get this behavior implicitly, but you can write a simple wrapper to make it easy to reuse without having to type out the consumer every time:

```tsx
import clsx from 'clsx';
import { Icon, IconContext, IconProps, Cube } from '@phosphor-icons/react';

const WithCtxClass = (props: IconProps & { icon: Icon }) => {
  const { icon: I, ...rest } = props;
  return (
    <IconContext.Consumer>
      {/* Important that the rest props come first, otherwise ctx will override explicit props */}
      {({ className }) => (<I {...rest} className={clsx(className, props.className)} />)}
    </IconContext.Consumer>
  );
};

const App = () => {
  return (
    <IconContext.Provider value={{ size: 48, className: "icon" }}>
      <WithCtxClass icon={Cube} className="foo" />
    </IconContext.Provider>
  );
};
```

Or, you can make a factory function to prepare the wrapped icons beforehand:

```tsx
function withCtxClass(icon: Icon) {
  return (props: IconProps) =>  {
    return (
      <IconContext.Consumer>
        {({ className }) => (<I {...props} className={clsx(className, props.className)} />)}
      </IconContext.Consumer>
    );
  }
}

const CombinedCube = withCtxClass(Cube);

const App = () => {
  return (
    <IconContext.Provider value={{ size: 48, className: "icon" }}>
      <CombinedCube className="foo" />
    </IconContext.Provider>
  );
};
```

**Comment by rektdeckard** [comment]
[Working demo](https://stackblitz.com/edit/stackblitz-starters-okwr9s?file=src%2Fstyle.css,src%2FApp.tsx)

**Comment by killface** [comment]
I really appreciate the examples! It still feels a lot of effort just to add a class to every icon.

I hear what you're saying about overwriting props being the default/expected behavior in React and JS, but I don't believe it's uncommon to treat a prop like `className` differently. I feel like this fits a little better with CSS's tendency toward "inheritance", and practically-speaking is more often what an engineer probably wants.

I think your argument for simply concatenating the two classNames is perfectly reasonable, too. What about something like:
```
className={[contextClassName, className].filter(Boolean).join(" ")}
```
or
```
  const theSpaceBetween = contextClassName && className ? " " : "";
  <svg
     className={contextClassName + theSpaceBetween + className}
     ...
```

I suppose changing this behavior _could_ possibly break someone else's current implementation if they're relying on the instance className to overwrite the context className. It seems unlikely, but to be safe I suppose this might have to be opt-in.

Alternatively, what if you just added a class like `ph` or `phosphor` to every icon by default and we could use that?

**Comment by rektdeckard** [comment]
I totally appreciate your need here. All the same, what you're proposing is unfortunately not really "reactish". It more closely resembles inheritance rather than composition. A good counterexample is to ask how would someone *omit* the context class, if they needed to in a specific case? It wouldn't be possible. That indicates a flaw in API design, in my opinion. Plus, as a popular library, we will always try our best not to break anyone's applications, ever. And given our number of users, someone is surely relying on the existing behavior, somewhere.

Your question pertains to CSS, which by definition, grants inheritance. If you don't like a React-based wrapper solution, why not simply use CSS as it was intended, to target the elements you need?

```tsx
<div className="something">
  <div>
    <div>
      <Cube className="icon" />
    </div>
  </div>
</div>
```

```css
.something svg.icon {
 transform: rotate(45deg);
}
```

**Comment by rektdeckard** [comment]
Or you could simply...you know...add the class to the element?

FWIW, I *do* believe it is extremely unexpected for `className`, or any other intrinsic HTMLAttribute prop, to have its behavior hijacked and modified. Our icons are specifically designed to be transparent, meaning a `<Cube />` exposes all of the underlying props/attributes of an `<svg />`, including being `forwardRef`s. Behavior is only *added*, never *changed*.

**Comment by killface** [comment]
Alas, I was really hoping for a simple way to apply a single class to every Phosphor icon. Seems that's not in the cards. Thanks for your time.

**Comment by vincerubinetti** [comment]
> AFAIC this is the expected behavior in React -- passing explicit props always overrides, not adds.

> what you're proposing is unfortunately not really "reactish". It more closely resembles inheritance rather than composition.

I disagree. The "always" is for the developer to explicitly specify the overriding/adding behavior, e.g. with `clsx`. Sure, it's common for a _library_ (e.g. a MUI dropdown component) to spread props like `{...props}` (overriding), but it's not all the time, and it's not necessarily fundamental at a React level.

> FWIW, I do believe it is extremely unexpected for className, or any other intrinsic HTMLAttribute prop, to have its behavior hijacked and modified. 

I definitely think this is true, though. The developer should be in control of this.

> A good counterexample is to ask how would someone omit the context class, if they needed to in a specific case? It wouldn't be possible.

I think a common API design to handle these flexibly is to accept either a string/raw value, or a function that gets passed the current value and allows you to return the desired value:

```tsx
<IconContext.Provider value={{ className: (prev) => clsx(prev, "icon-class") }} />
```

> Or you could simply...you know...add the class to the element?

This might seem like common sense, but breaks down on larger teams where the probability of forgetting to add the class (or multiple classes) is higher, and the consequences can actually be pretty breaking, e.g. a giant svg covering the entire screen.
