### ISSUE TITLE
React warning after update to 2.1.4

### ISSUE THREAD

**Issue by ivan-kleshnin** [phosphor-icons/react#93]
### Describe the bug

After an update from 2.1.3 to 2.1.4 (but also NextJS/React updates so I can't precisely trace the reason) I've started to receive this warning:

```
Warning: React does not recognize the `dataSlot` prop on a DOM element. 
If you intentionally want it to appear in the DOM as a custom attribute, 
spell it as lowercase `dataslot` instead. If you accidentally passed 
it from a parent component, remove it from the DOM element.
    at svg
    at IconBase
    at HiOutlineUsers
    at div
```

I don't have `dataSlot` anywhere in the code so it should be something internal to the library.

**Comment by rektdeckard** [comment]
We don't use this prop either, but we do respect spread props. I'm going to assume you are using `react-icons` and that this issue is identical to https://github.com/react-icons/react-icons/issues/931.
