### ISSUE TITLE
Issue updating past 2.1.3

### ISSUE THREAD

**Issue by johnnyshankman** [phosphor-icons/react#94]
**Describe the bug**

After updating from 2.1.3 to 2.1.4 I can no longer run my vitests within a react 18 + node v20 + vite 5 repo, as phosphor starts throwing import errors.

**Steps to Reproduce**

Upgrade from 2.1.3 to 2.1.4 and watch vitest fail to resolve imports within phosphor.

**Expected behavior**

No import issues in vitest, like in 2.1.3. 

**Screenshots**

**Context (please complete the following information):**
```
    "react": "^18.0.0",
    "react-dom": "^18.0.0",
    "react-router-dom": "^6.3.0"
    "@phosphor-icons/react": "2.1.4",
    "vite": "^5.2.7",
    "vitest": "^1.4.0",
```    

![Screenshot 2024-04-16 at 12 38 42 PM](https://github.com/phosphor-icons/react/assets/6632701/d2208285-aa70-4f8b-8d94-e01809115e1f)

```
Error: Cannot find package '/Users/johnshankman/Documents/manifoldxyz/studio-app-devtools/node_modules/@phosphor-icons/react/dist/node_modules/.pnpm/react@18.2.0/node_modules/react/package.json' imported from /Users/johnshankman/Documents/manifoldxyz/studio-app-devtools/node_modules/@phosphor-icons/react/dist/node_modules/.pnpm/react@18.2.0/node_modules/react/cjs/react-jsx-runtime.production.min.mjs
Did you mean to import react/index.js?
```

**Additional notes**

Downgrading back to 2.1.0 exactly produces no issues.

**Comment by rektdeckard** [comment]
Identified to be same issue as #90. Closing as duplicate, but fix incoming!

**Comment by johnnyshankman** [comment]
@rektdeckard thank you! cheers. apologies for the dupe.
